# Namespace config (like workspace/project)
apiVersion: v1
kind: Namespace
metadata:
  name: younessennadj-namespace
---
# Deploy container/pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-university-pod-deploy # Gave something unique to stand out but not referenced
  namespace: younessennadj-namespace
spec:
  selector:
    matchLabels:
      app: ai-department-app
  replicas: 2
  template:
    metadata:
      labels:
        app: ai-department-app # This will be referenced by service
    spec:
      containers:
      - name: ai-department-container # not referenced but for future usage
        image: younessennadj/pe_docker_image:latest
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "250m"
        ports:
        - containerPort: 3000
---
# deploy service which configures 
apiVersion: v1
kind: Service
metadata:
  name: younessennadj-svc
  namespace: younessennadj-namespace 
spec:
  selector:
    app: ai-department-app # referencing deployed deployment: Deployment > spec.template.metadata.labels.app  
  ports:
  - protocol: "TCP"
    port: 6000 # Ingress will connect to this port
    targetPort: 3000
  type: ClusterIP
---
# if you are using docker driver or want to use minikube add-on ingress:
# be sure to enabled ingress on minikube “minikube addons enable ingress”
# and run "minkube tunnel" on seperate terminal
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: city-university-ing
  namespace: younessennadj-namespace
  annotations:
    spec.ingressClassName: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http: # any connection comming through port 80
        paths:
          - pathType: ImplementationSpecific
            path: / 
            backend:
              service:
                name: younessennadj-svc
                port: 
                  number: 6000 # this is to access service not external exposed port
          # example of adding some other service
          #- pathType: ImplementationSpecific
          #  path: /some_other_svc
          #  backend:
          #    service:
          #      name: some-other-svc
          #      port: 
          #        number: 80